on:
  release:
    types: [created]
jobs:
  build:
    env:
      BUILD_ENV: production
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.CI_REPOSITORY_ACCESS_TOKEN }}

      - name: Setup NodeJS 14
        uses: actions/setup-node@v1
        with:
          node-version: 14
      
      - name: Setup Git Config 
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

      - name: Promote to prod
        run: |
          git checkout master
          npm run build $$ npm run publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      
      - name: Push changes rs-marine-services
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.CI_REPOSITORY_ACCESS_TOKEN }}
  